# Generated by Django 3.1.2 on 2020-10-25 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True, verbose_name='Duration in Minutes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='time_tracker.project')),
            ],
        ),
    ]
